window.golbalSetting = {
    //"CMAPI" : "", //nginx
    "CMAPI": "http://hive.sobey.com:9023",

    //"CM": "/CM",//nginx
    "CM": "http://hive.sobey.com:9021",

    //"TMSERVICE" : "/TMSERVICE",//nginx
    "TMSERVICE": "http://hive.sobey.com:9047",

    //"FL" : "/FL",//nginx
    "FL": "http://hive.sobey.com:9033",

    //"JOVE" : "/JOVE", //nginx for link
    "JOVE": "http://hive.sobey.com:9027/",

    //"TMWEB" : "/TMWEB"//nginx   for link
    "TMWEB": "http://hive.sobey.com:9049/",

    "FAVSWITCH": true

};
window._language = {
    "en": {
        "content": "Content",
        "effect": "Effect",
        "pageTitle": "Web Quick Editing",
        "baseClass": "Base class must override the name method, return the plugin name.",
        "plugin": "Plugin: ",
        "repeat": " repeat",
        "trackBelongOthers": "There are other media on the track, please remove it first.",
        "trackNotExist": "The track does not exist.",
        "empty": "Empty",
        "buffering": "Buffering...",
        "errorOfNetwork": "Error: network error",
        "errorOfMedia": "Error: media format error, unable to decode",
        "errorOfResource": "Error: unable to access media resources",
        "error": "error",
        "projectInfo": "Project information",
        "name": "Name",
        "unnamed": "Unnamed",
        "frameRate": "Frame rate",
        "breadth": "Breadth",
        "video": "Video",
        "audio": "Audio",
        "subtitle": "Subtitle",
        "picture": "Image",
        "trackBelongOtherLayer": "The track item has already belonged to a layer, please remove the binding first.",
        "adjustInOutPoint": "Adjust in/out point",
        "addItemL": "Add item[",
        "addItemR": "]",
        "insertItem": "Insert item",
        "adjustItemLoc": "Adjust item location",
        "moveItem": "Move item",
        "deleteItem": "Delete item",
        "wrongStart": "Wrong Start Time",
        "wrongEnd": "Wrong End Time",
        "startTimeGreater": "Start time is greater than the end time",
        "subclassMustType": "Subclasses must override the PopcornPlugin type",
        "subclassMustName": "Subclasses must override the name",
        "operation": "Operation",
        "colorUpdateError": "Color update error",
        "colorValueError": "Color value error",
        "theEditorL": "The Editor \"",
        "theEditorR": "\" does not exist.",
        "editorLayoutWrong": "The layout of editor is wrong",
        "MSYH": "Microsoft YaHei",
        "song": "SimSun",
        "startTimeError": "Start time error, has adjusted automatically",
        "endTimeError": "End time error, has adjusted automatically",
        "default": "Set as default",
        "second": "Second",
        "noMetadata": "With no metadata",
        "fade": "Fade-in/Fade-out",
        "flashBlack": "Flash Black",
        "flashWhite": "Flash White",
        "markPointM": "Add Marker(M)",
        "tip": "Tip",
        "markPointEmpty": "The Mark point remark can't be empty",
        "markPoint": "Mark List",
        "property": "Property",
        "displayPropertyInfo": "Display the Property Information of active object",
        "modifyE": "Modify program information(E)",
        "newN": "New(Ctrl+E)",
        "timelineEmpty": "The timeline is not empty, do you want to save it first?",
        "clearTimeline": "Are you sure to clear out the timeline?",
        "saveS": "Save(S)",
        "revokeZ": "Undo(Ctrl+Z)",
        "redoR": "Redo(Ctrl+Y)",
        "addSubtitleT": "Add Subtitle(T)",
        "subtitleExisted": "The current area has already existed the subtitle, please add the caption in the blank area.",
        "tobegin": "To the beginning(Home)",
        "lastFrame": "Last frame(←)",
        "playOrPause": "Play/Pause(Space)",
        "nextFrame": "Next frame(→)",
        "toEnd": "To the end(End)",
        "inL": "In([)",
        "outR": "Out(])",
        "cut": "Split(P)",
        "delete": "Delete(Delete)",
        "yes": "Yes",
        "no": "No",
        "confirm": "Confirm",
        "cancel": "Cancel",
        "inOrOutPoint": "In/Out point",
        "in": "In",
        "out": "Out",
        "markInGreater": "Mark In time is greater than Mark Out time.",
        "markoutLess": "Mark Out time is less than Mark In time.",
        "remarkEmpty": "The Mark point remark can't be empty.",
        "selectMarkPoint": "Please select the mark point!",
        "welcomeToUse": "Welcome to use the artDialog dialog components!",
        "welcome": "Welcome ",
        "description": "Comments",
        "buffer": "Buffering",
        "dragToChange": "Drag to change the current time.",
        "clickOrDblclick": "Click the lock / unlock, double click to lock the other tracks(Except the current track)",
        "createTime": "Create time",
        "markPointRemark": "Mark point remark:",
        "edit": "Video",
        "programInfo": "Program Information",
        "textEditor": "Text editor",
        "basic": "Basic",
        "advanced": "Advanced",
        "warning": "Warning:",
        "pressEnter": "Press Enter to Confirm",
        "mediaElement": "Media Element",
        "start": "Start",
        "end": "End",
        "active": "Active",
        "showOrHide": "Show / hide",
        "wrongTimeFormat": "Wrong time format",
        "create": "Create",
        "timelineEmptyNotSave": "The timeline is empty, can't be saved!",
        "success": "Success",
        "saveSuccess": "Save success!",
        "saveFailed": "Save failed!\n",
        "errorUp": "Error",
        "notSetSaveMethod": "Didn't set the save method, can't save the timeline.",
        "initializeFirst": "Please initialize first",
        "signatureTimeout": "Signature timeout, please regenerate a new signature.",
        "generateSignature": "Generate signature:",
        "preload": "Pre-load the next material...",
        "notSupportL": "Can't support the ",
        "notSupportR": " TrackEvent",
        "text": "Text",
        "customize": "Customize",
        "center": "Center",
        "bottom": "Bottom",
        "top": "Top",
        "textPosition": "Text position",
        "left": "Left",
        "right": "Right",
        "alignment": "Alignment",
        "finish": "Finish",
        "font": "Font",
        "fontSize": "Font Size",
        "fontColor": "Font Color",
        "shadow": "Shadow",
        "shadowColor": "Shadow Color",
        "background": "Background",
        "backgroundColor": "Background Color",
        "boldface": "Boldface",
        "italic": "Italic",
        "leftMargin": "Left Margin",
        "topMargin": "Top Margin",
        "width": "Width",
        "address": "Address",
        "height": "Height",
        "color": "Color",
        "sum": "Sum",
        "subtract": "Subtract",
        "multiply": "Multiply",
        "normal": "Normal",
        "renderMethod": "Render method",
        "transition": "Transition",
        "sendToRender": "Send to render",
        "ok": "OK",
        "startAt": "Start at",
        "target": "Target",
        "addSubtitle": "Double click to add subtitle.",
        "search": "search",
        "directory": "Directory",
        "title": "Title",
        "saveAsEdl": "Save As New EDL",
        "saveAsClip": "Save As Clip",
        "clearOut": "Clear out(\\)",
        "confirmFlag": "Confirm",
        "share": "Share",
        "export": "Export to 3rd Party",
        "register": "Register to OA",
        "renderSuccess": "Save as clip success!",
        "saveTileLineSuccess": "Save timeline success!",
        "saveTileLineFailed": "Save timeline Failed!",
        "notGetStream": "Can not get clip stream info!",
        "notGetFormat": "Can not find format info!",
        "getClipInfoFailed": "Get clip info failed!",
        "loadTimelineFailed": "Load Timeline failed",
        "emptyFolderList": "Empty folder list!",
        "getFolderListFailed": "Get folder list failed!",
        "openFolderFailed": "Open folder failed!",
        "getClipListFailed": "Get clip list failed!",
        "emptyResult": "Empty result!",
        "logout": "Close",
        "help": "Help",
        "sort": "Sort",
        "advancesearch": "Advance Search",
        "time": "Create Time",
        "type": "Type",
        "mv": "MV",
        "sv": "SV",
        "saveEdl": "Update the EDL",
        "timeLineEmpty": "Timeline is empty!",
        "renderFailed": "Save as clip failed!",
        "updateSuccessfully": "EDL update successfully!",
        "updatefailed": "EDL update failed!",
        "selectPath": "Save path can not be empty!",
        "noLengthInfo": "Can't get the length info!",
        "taskmonitor": "Task Monitor",
        "timeLineIsEmpty": "The timeline is empty, can't be saved!",
        "canNotAdd": "Can not add to timeline!",
        "errorWord": " Can't contain the illegal characters!",
        "pos": "POS",
        "emark": "Essence Mark",
        "smark": "Scene Mark",
        "cmark": "Change Mark",
        "fav": "Favorite",
        "isShowVideoStandard": false,
        "isShowSizes": false
    },
    "zh": {
        "content": "内容",
        "effect": "影响",
        "pageTitle": "快编",
        "baseClass": "基类必须重写命名方法，并返回插件名",
        "plugin": "插件: ",
        "repeat": " 循环播放",
        "trackBelongOthers": "时间线上有素材，请先保存",
        "trackNotExist": "时间线不存在",
        "empty": "空",
        "buffering": "缓冲中...",
        "errorOfNetwork": "错误：网络错误",
        "errorOfMedia": "错误：媒体格式错误，无法解码",
        "errorOfResource": "错误：获取素材失败",
        "error": "错误",
        "projectInfo": "工程文件信息",
        "name": "标题",
        "unnamed": "未命名",
        "frameRate": "帧率",
        "breadth": "Breadth",
        "video": "视频",
        "audio": "音频",
        "subtitle": "字幕",
        "picture": "图片",
        "trackBelongOtherLayer": "轨道上已有一个项目，请先删除.",
        "adjustInOutPoint": "调整入出点",
        "addItemL": "添加像[",
        "addItemR": "]",
        "insertItem": "插入项",
        "adjustItemLoc": "调整项目位置",
        "moveItem": "移动项",
        "deleteItem": "删除项",
        "wrongStart": "错误的开始时间",
        "wrongEnd": "错误的结束时间",
        "startTimeGreater": "开始时间大于结束时间",
        "subclassMustType": "子类必须覆盖PopcornPlugin类型",
        "subclassMustName": "子类必须重写名称",
        "operation": "操作",
        "colorUpdateError": "颜色更新错误",
        "colorValueError": "颜色值错误",
        "theEditorL": "错误 \"",
        "theEditorR": "\" 不存在",
        "editorLayoutWrong": "编辑布局错误",
        "MSYH": "微软雅黑",
        "song": "SimSun",
        "startTimeError": "开始时间错误，已自动调整",
        "endTimeError": "结束时间错误，已自动调整",
        "default": "默认值",
        "second": "秒",
        "noMetadata": "没有元数据",
        "fade": "淡入淡出",
        "flashBlack": "闪黑",
        "flashWhite": "闪白",
        "markPointM": "标记点(M)",
        "tip": "提示",
        "markPointEmpty": "标记点备注不能为空",
        "markPoint": "标记点",
        "property": "属性",
        "displayPropertyInfo": "显示对象属性信息",
        "modifyE": "修改项目信息(E)",
        "newN": "新建(Ctrl+E)",
        "timelineEmpty": "时间线不为空，是否需要先保存?",
        "clearTimeline": "确定清空时间线?",
        "saveS": "保存(S)",
        "revokeZ": "撤销(Ctrl+Z)",
        "redoR": "重做(Ctrl+Y)",
        "addSubtitleT": "添加字幕(T)",
        "subtitleExisted": "当前区域已存在字幕，请在空白区域添加标题",
        "tobegin": "到起始位置(Home)",
        "lastFrame": "前一帧(←)",
        "playOrPause": "播放/暂停(Space)",
        "nextFrame": "后一帧(→)",
        "toEnd": "到结束位置(End)",
        "inL": "入点([)",
        "outR": "出点(])",
        "cut": "剪切(P)",
        "delete": "删除(Delete)",
        "yes": "是",
        "no": "否",
        "confirm": "确定",
        "cancel": "取消",
        "inOrOutPoint": "入\\出点",
        "in": "入",
        "out": "出",
        "markInGreater": "入点大于出点",
        "markoutLess": "出点大于入点.",
        "remarkEmpty": "标记点备注不能为空.",
        "selectMarkPoint": "请选择标记点!",
        "welcomeToUse": "欢迎使用artDialog对话框组件!",
        "welcome": "欢迎你 ",
        "description": "注释",
        "buffer": "缓冲",
        "dragToChange": "拖动更改当前时间.",
        "clickOrDblclick": "点击锁定 / 解锁, 双击锁定其他轨道(除了当前轨道)",
        "createTime": "创建时间",
        "markPointRemark": "标记备注:",
        "edit": "编辑",
        "programInfo": "项目信息",
        "textEditor": "文本编辑器",
        "basic": "基础",
        "advanced": "高级",
        "warning": "警告:",
        "pressEnter": "Enter键确认",
        "mediaElement": "媒体素材",
        "start": "开始",
        "end": "结束",
        "active": "活动",
        "showOrHide": "显示 / 隐藏",
        "wrongTimeFormat": "错误的时间格式",
        "create": "创建",
        "timelineEmptyNotSave": "时间线为空，不能保存!",
        "success": "成功",
        "saveSuccess": "保存成功!",
        "saveFailed": "保存失败!\n",
        "errorUp": "错误",
        "notSetSaveMethod": "没有设置保存方式，无法保存时间线.",
        "initializeFirst": "请先初始化",
        "signatureTimeout": "签名超时，请重新生成签名.",
        "generateSignature": "生成签名:",
        "preload": "预加载下一个素材...",
        "notSupportL": "不支持L ",
        "notSupportR": " TrackEvent",
        "text": "文本",
        "customize": "自定义",
        "center": "居中",
        "bottom": "底部",
        "top": "顶部",
        "textPosition": "文本位置",
        "left": "左对齐",
        "right": "右对齐",
        "alignment": "对齐方式",
        "finish": "完成",
        "font": "字体",
        "fontSize": "字体大小",
        "fontColor": "字体颜色",
        "shadow": "阴影",
        "shadowColor": "阴影颜色",
        "background": "背景",
        "backgroundColor": "背景颜色",
        "boldface": "加粗",
        "italic": "斜体",
        "leftMargin": "左边距",
        "topMargin": "上边距",
        "width": "宽度",
        "address": "地址",
        "height": "高度",
        "color": "颜色",
        "sum": "加",
        "subtract": "减",
        "multiply": "加倍",
        "normal": "标准",
        "renderMethod": "合成方式",
        "transition": "转场",
        "sendToRender": "发送到合成",
        "ok": "OK",
        "startAt": "开始于",
        "target": "目标",
        "addSubtitle": "双击添加字幕.",
        "search": "搜索",
        "directory": "目录",
        "title": "标题",
        "saveAsEdl": "另存时间线",
        "saveAsClip": "保存为素材",
        "clearOut": "清空(\\)",
        "confirmFlag": "确认",
        "share": "分享",
        "export": "导出到第三方系统",
        "register": "注册OA",
        "renderSuccess": "保存素材成功!",
        "saveTileLineSuccess": "保存时间线成功!",
        "saveTileLineFailed": "保存时间线失败!",
        "notGetStream": "未获取到视音频流信息!",
        "notGetFormat": "未获取到视音频格式信息!",
        "getClipInfoFailed": "获取素材信息失败!",
        "loadTimelineFailed": "加载时间线失败",
        "emptyFolderList": "未获取到目录树!",
        "getFolderListFailed": "获取目录树失败!",
        "openFolderFailed": "打开文件夹失败!",
        "getClipListFailed": "获取素材列表失败!",
        "emptyResult": "未检索到结果!",
        "logout": "退出",
        "help": "帮助",
        "sort": "排序",
        "advancesearch": "高级搜索",
        "time": "创建时间线",
        "type": "类型",
        "mv": "MV",
        "sv": "SV",
        "saveEdl": "保存时间线",
        "timeLineEmpty": "时间线为空!",
        "renderFailed": "保存素材失败!",
        "updateSuccessfully": "时间线更新成功!",
        "updatefailed": "时间线更新失败!",
        "selectPath": "保存路径不能为空!",
        "noLengthInfo": "长度信息获取失败!",
        "taskmonitor": "任务监听",
        "timeLineIsEmpty": "时间线为空，不能保存!",
        "canNotAdd": "添加到时间线失败!",
        "errorWord": "不能包含非法字符!",
        "pos": "位置",
        "emark": "Essence标记",
        "smark": "场景标记",
        "cmark": "转场标记",
        "isShowVideoStandard": false,
        "isShowSizes": false,
        "fav": "收藏夹"
    }
}
